Resources:

* https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

* https://www.learnpytorch.io/00_pytorch_fundamentals/

* https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32668448#learning-tools
* https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
* https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb `link for ex in github`
  


PyTorch 00

In [1]:
import torch 
from torch import nn, optim 
from torchvision import datasets, transforms
import torch.nn.functional as F
import numpy as np

In [2]:
device ='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

### Random Tesnsor 

`torch-->tensor-->is amazing`

In [3]:
import datetime
print('last update: ', datetime.datetime.now())

last update:  2024-05-24 17:21:44.522826


In [13]:
Matrix = torch.randn(size=(2,2))
Matrix

tensor([[ 1.1335, -1.1947],
        [-0.1580,  0.9890]])

In [16]:
K = torch.rand(size=(2, 2))
K

tensor([[0.9560, 0.1433],
        [0.1081, 0.9746]])

In [19]:
# range tensor
range_tensor = torch.arange(start=0, end=10, step=1)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# crate a tensor similar to range tensor with zeros
zeros_like = torch.zeros_like(range_tensor)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
# verify 
range_tensor.shape == zeros_like.shape # True
range_tensor is zeros_like

False

# Dtype
There are several datatypes in PyTorch i.e.: float and int, it is for precisions in computing. The float are more precise, hence, more precise in carying information and need more computing power. 
Precision: is the amount of details used to describe a number. The higher the number (8, 16, 32, 64 and ...) is more detail and data is used to express a number.

In [35]:
tensor_float32 = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False) # if True then operation performed will be recorded
p = tensor_float32.shape, tensor_float32.dtype, tensor_float32.device                              
print(p)
type(p)

(torch.Size([3]), torch.float32, device(type='cpu'))


tuple

In [36]:
# Often Pytorch likes tensors be stored on same device, by default on cpu, and be same datatype. 
# If got stuck on tensors song: what shape,what datatype, where where where?
# in deep learning, the ML model: starts(initialization)--> look at data (representation) --> update (optimization)

In [53]:
# Operations
# All below operations are element-wise
t = torch.tensor([1, 2, 3])
t - 10
t
t + 10
t
t = t -10
t
t
t * t
t
# Note the tensor does not change unless modify it explicitly. 

tensor([-9, -8, -7])

In [58]:
# Multiplication: all we need 
# element wise
t1 = torch.tensor([1, 2, 3])

print(t1 * t1) # element wise
print(torch.matmul(t1, t1)) # matrix multiplication

tensor([1, 4, 9])
tensor(14)


In [61]:
%%time
v = 0
for i in range(len(t1)):
    v += t1[i] * t1[i]

# print(v)
v

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [62]:
%%time
torch.matmul(t1, t1)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [63]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [64]:
# short form for matmul is mm
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [71]:
# Aggregation ===> sum ,min, max, etc.
# Create a new tensor 
s = torch.arange(0, 100, 10)
ss = s.min(), s.max(), s.sum()
type(ss) # tuple

# check does operations handled with pytorch or python
type = tuple(type(value) for value in ss)
type

(torch.Tensor, torch.Tensor, torch.Tensor)

In [77]:
# Positional max/ min==> returns the position(index) not the value
print(f"position where max is: {torch.argmax(s)}") # this is API
print(f" pos for max is : {s.argmax()}") # this is OOP method
# print(assert torch.argmax(s) == s.argmax()) ==> assert evaluates the condition, thus, raises error as assert returns nothing, 
# iff the condition does not hold, evaluates to False it raises 'AssertionError'. 
assert torch.argmax(s) == s.argmax()

position where max is: 9
 pos for max is : 9


### Reshaping, View, Stacking, Squeeze, & Unsqueez
Reshaping: reshape tensor to defined shape

View: Returns a view of a tensor but `keep memory same`,--> shares the same memory with the original tensor. 

Stacking: concatenate multiple tensor on: top of each other `vstack`-->vertical stack or side by side `hstack`-->horizontal stack. 

Squeeze: removes all `1` dimensions from a tensor. 

Unsqueeze: ADD `1` dimension to the target tensor. 

Permute: returns view of a tensor with the swapped dimensions in a certain way.

In [108]:
# create a tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [94]:
# Reshape x; Keep in mind that the new shapes must be compatible. The number of elements must satisfy the reshape. 
x1_reshaped = x.view(2, 5)
x2_reshaped = x.reshape(2, 5)
print(x1_reshaped == x2_reshaped) # the equality operator compares values/ contents. 
x1_reshaped is x2_reshaped # 'is' operator checks whether 2 variables point to the same object in memory(object identity).
# It does not compare values or contents.
print(torch.equal(x1_reshaped, x2_reshaped)) # special function to compare values in torch.

tensor([[True, True, True, True, True],
        [True, True, True, True, True]])
True


In [109]:
x_reshape = x.reshape(1, 10)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [110]:
# view shares the same memory with original tensor. So, x and y share same memory==> changes in y are changes in x
y = x.view(1, 10)
y, y.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [111]:
y[:, 0] = 99
x, y

(tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [112]:
# Stack tesnsors on top of each other
x_stacked = torch.stack([x, x, x]) # stack function accepts list of tensors, dim=0 by default 
x_stacked

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [113]:
x_stacked_dim1 = torch.stack([x, x], dim=1)# dim=1 thus side by side
x_stacked_dim1

tensor([[99., 99.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.],
        [10., 10.]])

In [123]:
# Squeeze removes all single dimensions from target tensor
x_squeezed = torch.squeeze(x)
x_squeezed
torch.equal(x_squeezed , x) # x doesnt have size 1

True

In [125]:
# create new tensor 
x_one = torch.zeros(1, 2, 3, 1, 2, 3)
x_one_squeezed = torch.squeeze(x_one)

print(f"The original shape is :{x_one.size()}")
print(f"Dimension after squeeze is : {x_one_squeezed.size()}")

The original shape is :torch.Size([1, 2, 3, 1, 2, 3])
Dimension after squeeze is : torch.Size([2, 3, 2, 3])


In [129]:
# Unsqueeze adds single dim at the specified dim
x_one_unsqueezed = torch.unsqueeze(x_one_squeezed, dim=0)
print(f" x_one_squeezed.shape is : {x_one_squeezed.size()}")
print(f" x_one_unsqueezed.shape is : {x_one_unsqueezed.size()}")

 x_one_squeezed.shape is : torch.Size([2, 3, 2, 3])
 x_one_unsqueezed.shape is : torch.Size([1, 2, 3, 2, 3])


# Rand & Randn


* Generate a tensor with shape (2, 3) from a normal distribution

tensor_randn = torch.randn(2, 3)

print(tensor_randn)


import torch

* Generate a tensor with shape (2, 3) from a uniform distribution

tensor_rand = torch.rand(2, 3)

print(tensor_rand)


In [137]:
# torch.permute() -> rearrange tensor in the specified dimensions in view 
x_img = torch.rand(size=(224, 224, 3))
x_img.shape

# lets rearrange dims to be: 3, 224,224 instead
x_img_permute = x_img.permute(2, 0, 1)
print("Original shape is :{}".format(x_img.shape))
print("Dim after permute is :{}".format(x_img_permute.size()))

Original shape is :torch.Size([224, 224, 3])
Dim after permute is :torch.Size([3, 224, 224])


### Indexing 

In [140]:
# Create a tensor 
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [143]:
# Index in the outer bracket--> dim=0
x[0]
# x[1] IndexError: index 1 is out of bounds for dimension 0 with size 1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [169]:
# Indexing the middle brackets--> dim=1
print(x[0][0])
print(x[0, 0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [146]:
# Indexing the first element
x[0][0][0]

tensor(1)

In [170]:
# Index 9
x[0][2][2]

tensor(9)

In [171]:
# Index 4
x[0][1][0]

tensor(4)

In [172]:
# Index 7, 8, 9
x[0][2]

tensor([7, 8, 9])

In [175]:
# Indexing can be ':' for all of the selected dims
print(x[:, 0])
x[:, 0].shape

tensor([[1, 2, 3]])


torch.Size([1, 3])

In [176]:
# get all values of 0th & 1st dim but only index 1 & 2nd dims
x[:, :, 1]

tensor([[2, 5, 8]])

In [153]:
d1 = torch.arange(1, 13)
print(d1.shape)
d = torch.arange(1, 13).reshape(1, 3, 2, 2)
d.shape

torch.Size([12])


torch.Size([1, 3, 2, 2])

In [154]:
d.reshape(1, 6, 2)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [168]:
e = torch.arange(1, 14)
print(e.shape)
# e is singletone dim. only possible to have inference by: 
e_inf = e.reshape((-1,))
print(e_inf.size())
e_n = e.reshape((-1, 1))
e_n.shape
"""Compatibility Rule: The total number of elements in the new shape must be the same as the original shape.
Use -1 for Inference: Use -1 in the shape to let PyTorch automatically infer a compatible dimension."""

torch.Size([13])
torch.Size([13])


'Compatibility Rule: The total number of elements in the new shape must be the same as the original shape.\nUse -1 for Inference: Use -1 in the shape to let PyTorch automatically infer a compatible dimension.'

## PyTorch <--> Numpy
Numpy array to PyTorch tensor `torch.from_numpy(ndarray)`

PyTorch tensor to Numpy array `torch.Tensor.numpy()`

tensor to numpy and vice verca--> They do not share memory, thus, changing tensor or array will not change tensor or array. 

Datatype: NumPy is float64, PyTorch is float32.

In [180]:
import numpy as np
array = np.arange(0.0, 8.0)
print(array.shape, array.dtype)

tensor_np = torch.from_numpy(array)
print(tensor_np, tensor_np.size(), tensor_np.dtype) # Warning: numpy default datatype is float64, however, pytorch default datatype is float32.

(8,) float64
tensor([0., 1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) torch.Size([8]) torch.float64


In [184]:
# modify tesnor_np to float32
tensor32 = tensor_np.type(torch.float32)
tensor32.dtype


torch.float32

In [186]:
# what will be occured by modifying array to tensor? Only the array will be changed!
array = array + 1
array, tensor_np

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [187]:
# tensor to NumPy array 
array_to_tensor = torch.Tensor.numpy(tensor_np)
array_to_tensor

array([0., 1., 2., 3., 4., 5., 6., 7.])

## Reproducibility

Taking random out of random!

In DL, ML the model starts with `random numbers `->`tensor operation`->`try to make better`. Meaning it is possible that every executions varies. However, randomness is powerfull. 

To reduce randomness in DNN PyTorch has concept of **Random Seed**. Essentially random seed **Falavour** the randomness. 

Random seed can be any int number such: 0, 42, 1234 and etc. 

Warning: random seed apply only on a block of code--> apply it before each line to catch.

Creating random tensor but with the same seed value, even in the different notebook would result the same tensors.

**The number of seed generates different outcomes, i.e. for the same tensor, 7 and 70 generates different values.**

In [188]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

In [189]:
random_tensor_A == random_tensor_B # the equal operator checks all values. 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [195]:
# Set the random seed
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_A == random_tensor_B # the equal operator checks all values. 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [196]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)
random_tensor_C == random_tensor_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [198]:
random_seed = 42
# Flavour tensor C by random seed
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3, 4)

# Flavour tensor D by random seed
torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3, 4)
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
cd  "C:\Users\Soheil\Desktop\pro3/"

## GPU

In [1]:
!nvidia-smi

Mon May 13 12:37:26 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 552.22                 Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   44C    P8             11W /  170W |     590MiB /  12288MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
# check for GPU access via pytorch 
import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code ===> check is there any GPU accessible? 

# set device
device = 'cuda' if torch.cuda.is_available else 'cpu'
device

'cuda'

In [6]:
# Count number of GPUs(devices)
torch.cuda.device_count()

1

## Putting tensors, models to GPU


In [8]:
# Create a tensor 
tensor = torch.tensor([1, 2, 3], device='cpu')
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [13]:
## If tensor is on gpu,we cant use tensor with NumPy as NumPy only is compatible with CPUs

# tranfer tensor to gpu
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

# transfer to numpy
np_tensor = tensor_on_gpu.numpy()

tensor([1, 2, 3], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [18]:
# torch has good errors explanation ==> Tensor.cpu() to copy the tensor to host memory first
np_tensor = tensor_on_gpu.to('cpu').numpy()
np_tensor #np_tensor.device

array([1, 2, 3], dtype=int64)

## after each chapter there is an exercise section to do: 
- https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises